<?php

use App\Support\ErpReportsCatalog;

/**
 * QuickBooks Desktop Enterprise–style main menubar.
 * Every entry opens an existing workspace route (or a shell action).
 *
 * @return array<string, list<array{label?: string, route?: string, action?: string, separator?: bool, children?: list<array<string, mixed>>, shortcut?: string, disabled?: bool, message?: string}>>
 */
return [
    'File' => [
        ['label' => 'New', 'children' => [
            ['label' => 'Invoice', 'route' => 'invoices.create'],
            ['label' => 'Sales Receipt', 'route' => 'sales-receipts.create'],
            ['label' => 'Estimate / Quote', 'route' => 'quotes.create'],
            ['label' => 'Sales Order', 'route' => 'sales-orders.create'],
            ['label' => 'Credit Memo / Refund', 'route' => 'credit-memos.create'],
            ['label' => 'Purchase Order', 'route' => 'purchase-orders.create'],
            ['label' => 'Bill', 'route' => 'vendor-bills.create'],
            ['label' => 'Check', 'route' => 'checks.create'],
            ['label' => 'Deposit', 'route' => 'deposits.create'],
            ['label' => 'Journal Entry', 'route' => 'accounting.journals'],
            ['separator' => true],
            ['label' => 'Customer', 'route' => 'customers.create'],
            ['label' => 'Vendor', 'route' => 'vendors.create'],
            ['label' => 'Item', 'route' => 'items.create'],
            ['label' => 'Bank Account', 'route' => 'banking.create'],
        ]],
        ['separator' => true],
        ['label' => 'Open Forms', 'children' => [
            ['label' => 'Invoices', 'route' => 'invoices.index'],
            ['label' => 'Sales Orders', 'route' => 'sales-orders.index'],
            ['label' => 'Estimates / Quotes', 'route' => 'quotes.index'],
            ['label' => 'Sales Receipts', 'route' => 'sales-receipts.index'],
            ['label' => 'Credit Memos', 'route' => 'credit-memos.index'],
            ['label' => 'Purchase Orders', 'route' => 'purchase-orders.index'],
            ['label' => 'Bills', 'route' => 'vendor-bills.index'],
            ['label' => 'Item Receipts', 'route' => 'goods-receipts.index'],
            ['label' => 'Checks', 'route' => 'checks.index'],
            ['label' => 'Deposits', 'route' => 'deposits.index'],
        ]],
        ['separator' => true],
        ['label' => 'Print Forms', 'children' => [
            ['label' => 'Invoices', 'route' => 'invoices.index'],
            ['label' => 'Sales Receipts', 'route' => 'sales-receipts.index'],
            ['label' => 'Statements', 'route' => 'customers.statements'],
            ['label' => 'Checks', 'route' => 'checks.index'],
            ['label' => 'Purchase Orders', 'route' => 'purchase-orders.index'],
        ]],
        ['separator' => true],
        ['label' => 'Import from JapsPOS…', 'route' => 'import.index'],
        ['label' => 'Utilities', 'children' => [
            ['label' => 'Audit Log', 'route' => 'audit.index'],
            ['label' => 'JapsPOS Import Wizard', 'route' => 'import.index'],
            ['label' => 'Verify Data (Audit)', 'route' => 'audit.index'],
        ]],
        ['separator' => true],
        ['label' => 'Company Information', 'route' => 'company.info'],
        ['label' => 'Preferences…', 'route' => 'settings.index'],
        ['separator' => true],
        ['label' => 'Exit / Sign Out', 'action' => 'logout'],
    ],

    'Edit' => [
        ['label' => 'Find Customers…', 'route' => 'customers.index'],
        ['label' => 'Find Vendors…', 'route' => 'vendors.index'],
        ['label' => 'Find Items…', 'route' => 'items.index'],
        ['label' => 'Find Invoices…', 'route' => 'invoices.index'],
        ['label' => 'Find Bills…', 'route' => 'vendor-bills.index'],
        ['label' => 'Find Checks…', 'route' => 'checks.index'],
        ['separator' => true],
        ['label' => 'Preferences…', 'route' => 'settings.index'],
    ],

    'View' => [
        ['label' => 'Home Page', 'route' => 'dashboard.home'],
        ['label' => 'Company Snapshot / Insights', 'route' => 'dashboard.snapshots'],
        ['label' => 'Calendar', 'route' => 'dashboard.snapshots'],
        ['separator' => true],
        ['label' => 'Income Tracker', 'route' => 'payments.index'],
        ['label' => 'Bill Tracker', 'route' => 'vendor-bills.index'],
        ['separator' => true],
        ['label' => 'Open Windows', 'action' => 'focus-tabs'],
        ['label' => 'Refresh Tab', 'action' => 'refresh-tab'],
    ],

    'Lists' => [
        ['label' => 'Chart of Accounts', 'route' => 'accounting.chart'],
        ['label' => 'Item List', 'route' => 'items.index'],
        ['separator' => true],
        ['label' => 'Customer Center', 'route' => 'customers.index'],
        ['label' => 'Vendor Center', 'route' => 'vendors.index'],
        ['separator' => true],
        ['label' => 'Payroll Item List', 'route' => 'employees.payroll'],
        ['label' => 'Templates', 'route' => 'settings.index'],
        ['label' => 'Memorized Transaction List', 'route' => 'reports.index'],
        ['separator' => true],
        ['label' => 'Customer & Vendor Profile Lists', 'children' => [
            ['label' => 'Payment Methods / Lookups', 'route' => 'lookups.index'],
            ['label' => 'Terms / Tax Codes / Units', 'route' => 'lookups.index'],
            ['label' => 'Price Levels', 'route' => 'lookups.index'],
            ['label' => 'Item Categories', 'route' => 'lookups.index'],
        ]],
        ['separator' => true],
        ['label' => 'Add/Edit Multiple List Entries', 'route' => 'lookups.index'],
        ['label' => 'Fixed Asset Item List', 'route' => 'accounting.chart'],
    ],

    'Favorites' => [
        ['label' => 'Create Invoices', 'route' => 'invoices.create'],
        ['label' => 'Receive Payments', 'route' => 'payments.create'],
        ['label' => 'Enter Bills', 'route' => 'vendor-bills.create'],
        ['label' => 'Pay Bills', 'route' => 'vendor-payments.create'],
        ['label' => 'Write Checks', 'route' => 'checks.create'],
        ['label' => 'Item List', 'route' => 'items.index'],
        ['label' => 'Customer Center', 'route' => 'customers.index'],
        ['label' => 'Vendor Center', 'route' => 'vendors.index'],
        ['label' => 'Report Center', 'route' => 'reports.index'],
        ['label' => 'Chart of Accounts', 'route' => 'accounting.chart'],
    ],

    'Mfg & Whsle' => [
        ['label' => 'Create Quotes (Estimates)', 'route' => 'quotes.create'],
        ['label' => 'Create Sales Orders', 'route' => 'sales-orders.create'],
        ['label' => 'Sales Order Fulfillment Worksheet', 'route' => 'sales-orders.fulfillment'],
        ['label' => 'Create Invoices', 'route' => 'invoices.create', 'shortcut' => 'Ctrl+I'],
        ['label' => 'Create Sales Receipts', 'route' => 'sales-receipts.create'],
        ['label' => 'Receive Payments', 'route' => 'payments.create'],
        ['label' => 'Make Deposits', 'route' => 'deposits.create'],
        ['separator' => true],
        ['label' => 'Create Purchase Orders', 'route' => 'purchase-orders.create'],
        ['label' => 'Receive Items', 'route' => 'goods-receipts.create'],
        ['label' => 'Return to Vendor (RTV)', 'route' => 'vendor-returns.create'],
        ['label' => 'Enter Bill for Received Items', 'route' => 'vendor-bills.create'],
        ['label' => 'Enter Bills', 'route' => 'vendor-bills.create'],
        ['label' => 'Pay Bills', 'route' => 'vendor-payments.create'],
        ['separator' => true],
        ['label' => 'Item List', 'route' => 'items.index'],
        [
            'label' => 'Inventory Activities',
            'children' => [
                ['label' => 'Inventory Stock Status', 'route' => 'inventory.index'],
                ['label' => 'Adjust Quantity/Value on Hand', 'route' => 'inventory.adjustments'],
                ['label' => 'Receive Inventory', 'route' => 'goods-receipts.create'],
                ['label' => 'Return to Vendor (RTV)', 'route' => 'vendor-returns.create'],
                ['label' => 'Build Assemblies', 'route' => 'inventory.adjustments'],
                ['label' => 'Change Item Prices', 'route' => 'items.index'],
            ],
        ],
        [
            'label' => 'Manufacturing and Wholesale Reports',
            'children' => ErpReportsCatalog::manufacturingWholesaleMenu(),
        ],
    ],

    'Company' => [
        ['label' => 'Home Page', 'route' => 'dashboard.home'],
        ['label' => 'Company Snapshot', 'route' => 'dashboard.snapshots'],
        ['label' => 'Calendar', 'route' => 'dashboard.snapshots'],
        ['label' => 'Documents / Audit Log', 'route' => 'audit.index'],
        ['separator' => true],
        ['label' => 'Company Information…', 'route' => 'company.info'],
        ['label' => 'Preferences…', 'route' => 'settings.index'],
        ['label' => 'Manage Sales Tax…', 'route' => 'settings.index'],
        ['separator' => true],
        ['label' => 'Chart of Accounts', 'route' => 'accounting.chart'],
        ['label' => 'Make General Journal Entries', 'route' => 'accounting.journals'],
        ['label' => 'Reconcile', 'route' => 'reconciliation.index'],
        ['separator' => true],
        ['label' => 'Planning & Budgeting', 'route' => 'reports.profit-loss'],
        ['label' => 'Set Up Users and Passwords', 'route' => 'profile'],
        ['separator' => true],
        ['label' => 'Import from JapsPOS…', 'route' => 'import.index'],
        ['label' => 'Audit Log', 'route' => 'audit.index'],
    ],

    'Customers' => [
        ['label' => 'Customer Center', 'route' => 'customers.index'],
        ['label' => 'Income Tracker', 'route' => 'payments.index'],
        ['separator' => true],
        ['label' => 'Create Estimates', 'route' => 'quotes.create'],
        ['label' => 'Create Sales Orders', 'route' => 'sales-orders.create'],
        ['label' => 'Sales Order Fulfillment Worksheet', 'route' => 'sales-orders.fulfillment'],
        ['label' => 'Create Invoices', 'route' => 'invoices.create'],
        ['label' => 'Create Sales Receipts', 'route' => 'sales-receipts.create'],
        ['label' => 'Enter Statement Charges', 'route' => 'invoices.create'],
        ['label' => 'Create Statements…', 'route' => 'customers.statements'],
        ['separator' => true],
        ['label' => 'Receive Payments', 'route' => 'payments.create'],
        ['label' => 'Credit Card Processing Activities', 'route' => 'payments.create'],
        ['label' => 'Create Credit Memos/Refunds', 'route' => 'credit-memos.create'],
        ['label' => 'Apply Credits / Refunds', 'route' => 'credit-memos.apply'],
        ['separator' => true],
        ['label' => 'Add / Edit Multiple Customers', 'route' => 'customers.index'],
        [
            'label' => 'Customer & Job Lists',
            'children' => [
                ['label' => 'Invoice List', 'route' => 'invoices.index'],
                ['label' => 'Estimates / Quotes', 'route' => 'quotes.index'],
                ['label' => 'Sales Orders', 'route' => 'sales-orders.index'],
                ['label' => 'SO Fulfillment Worksheet', 'route' => 'sales-orders.fulfillment'],
                ['label' => 'Sales Receipts', 'route' => 'sales-receipts.index'],
                ['label' => 'Credit Memos', 'route' => 'credit-memos.index'],
                ['label' => 'Payments', 'route' => 'payments.index'],
            ],
        ],
    ],

    'Vendors' => [
        ['label' => 'Vendor Center', 'route' => 'vendors.index'],
        ['label' => 'Bill Tracker', 'route' => 'vendor-bills.index'],
        ['separator' => true],
        ['label' => 'Enter Bills', 'route' => 'vendor-bills.create'],
        ['label' => 'Return to Vendor (RTV)', 'route' => 'vendor-returns.create'],
        ['label' => 'Pay Bills', 'route' => 'vendor-payments.create'],
        ['label' => 'Purchase Orders', 'route' => 'purchase-orders.create'],
        ['label' => 'Item Receipts', 'route' => 'goods-receipts.create'],
        ['label' => 'Enter Bill for Received Items', 'route' => 'vendor-bills.create'],
        ['separator' => true],
        [
            'label' => 'Inventory Activities',
            'children' => [
                ['label' => 'Adjust Quantity/Value on Hand', 'route' => 'inventory.adjustments'],
                ['label' => 'Inventory Stock Status', 'route' => 'inventory.index'],
                ['label' => 'Receive Items', 'route' => 'goods-receipts.create'],
                ['label' => 'Return to Vendor (RTV)', 'route' => 'vendor-returns.create'],
                ['label' => 'Change Item Prices', 'route' => 'items.index'],
            ],
        ],
        ['separator' => true],
        ['label' => 'Sales Tax', 'children' => [
            ['label' => 'Manage Sales Tax', 'route' => 'settings.index'],
            ['label' => 'Tax Codes / Lookups', 'route' => 'lookups.index'],
        ]],
        ['label' => 'Print / Review 1099s', 'route' => 'reports.vendor-balance'],
        ['separator' => true],
        [
            'label' => 'Vendor Lists',
            'children' => [
                ['label' => 'Purchase Order List', 'route' => 'purchase-orders.index'],
                ['label' => 'Bill List', 'route' => 'vendor-bills.index'],
                ['label' => 'Item Receipt List', 'route' => 'goods-receipts.index'],
                ['label' => 'Bill Payments', 'route' => 'vendor-payments.index'],
            ],
        ],
    ],

    'Employees' => [
        ['label' => 'Employee Center', 'route' => 'employees.payroll'],
        ['label' => 'Enter Time', 'route' => 'employees.time'],
        ['label' => 'Payroll Center', 'route' => 'employees.payroll'],
        ['label' => 'Pay Employees', 'route' => 'employees.payroll'],
        ['separator' => true],
        ['label' => 'Payroll Item List', 'route' => 'employees.payroll'],
        ['label' => 'Weekly Timesheet', 'route' => 'employees.time'],
    ],

    'Banking' => [
        ['label' => 'Write Checks', 'route' => 'checks.create'],
        ['label' => 'Order Checks', 'route' => 'checks.create'],
        ['label' => 'Enter Credit Card Charges', 'route' => 'vendor-bills.create'],
        ['label' => 'Make Deposits', 'route' => 'deposits.create'],
        ['label' => 'Transfer Funds', 'route' => 'banking.create'],
        ['separator' => true],
        ['label' => 'Reconcile', 'route' => 'reconciliation.index'],
        ['label' => 'Bank Feeds', 'route' => 'banking.index'],
        ['label' => 'Use Register', 'route' => 'checks.index'],
        ['label' => 'Check Register', 'route' => 'checks.index'],
        ['separator' => true],
        ['label' => 'Chart of Accounts', 'route' => 'accounting.chart'],
        ['label' => 'Make Journal Entries', 'route' => 'accounting.journals'],
        ['label' => 'Loan Manager', 'route' => 'banking.create'],
        ['separator' => true],
        ['label' => 'Bank Account List', 'route' => 'banking.index'],
        ['label' => 'Deposit List', 'route' => 'deposits.index'],
        ['label' => 'Check List', 'route' => 'checks.index'],
    ],

    'Reports' => ErpReportsCatalog::menubarItems(),

    'Window' => [
        ['label' => 'Home Page', 'route' => 'dashboard.home'],
        ['label' => 'Company Snapshot', 'route' => 'dashboard.snapshots'],
        ['separator' => true],
        ['label' => 'Close', 'action' => 'close-tab'],
        ['label' => 'Close All', 'action' => 'close-all'],
        ['label' => 'Close Others', 'action' => 'close-others'],
        ['separator' => true],
        ['label' => 'Refresh Tab', 'action' => 'refresh-tab'],
        ['label' => 'Open Windows', 'action' => 'focus-tabs'],
    ],

    'Help' => [
        ['label' => 'JapsPOS Help Topics', 'action' => 'toast', 'message' => 'Use Report Center and Home Page workflows — JapsPOS desktop POS menus.'],
        ['label' => 'App Center / Profile', 'route' => 'profile'],
        ['separator' => true],
        ['label' => 'About JapsPOS', 'action' => 'toast', 'message' => 'JapsPOS — developed for Bargain Enterprise wholesale distribution.'],
    ],
];
